"""add was_fallback to manager_messages

Revision ID: 07fc7b9d1512
Revises: b3c4d4c7e67e
Create Date: 2026-09-01 18:36:44.274885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fc7b9d1512'
down_revision: Union[str, Sequence[str], None] = 'b3c4d4c7e67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager_messages', sa.Column('was_fallback', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager_messages', 'was_fallback')
    # ### end Alembic commands ###
