"""sequential task flow: session sequence and task index

Revision ID: 0b6d83c2dfaa
Revises: 7ee70dd83a67
Create Date: 2026-09-16 17:31:48.546276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b6d83c2dfaa'
down_revision: Union[str, Sequence[str], None] = '7ee70dd83a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('task_sequence', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # server_default so this is safe to add to a table that already has
    # rows (existing sessions get position 0, same as a brand-new one with
    # no sequence to be positioned in yet).
    op.add_column('sessions', sa.Column('task_sequence_position', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sessions', sa.Column('max_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('sequence_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sequence_index')
    op.drop_column('sessions', 'max_duration_seconds')
    op.drop_column('sessions', 'task_sequence_position')
    op.drop_column('sessions', 'task_sequence')
    # ### end Alembic commands ###
