"""add email prioritization tables

Revision ID: 5d531d7e7924
Revises: 07fc7b9d1512
Create Date: 2026-09-15 15:51:37.622469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM as PGEnum

# revision identifiers, used by Alembic.
revision: str = '5d531d7e7924'
down_revision: Union[str, Sequence[str], None] = '07fc7b9d1512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate doesn't diff enum member sets against the live Postgres
    # type for an unchanged column -- same manual addition pattern as
    # b3c4d4c7e67e_add_image_matching_to_tasktype_enum.py. Pure addition,
    # safe outside the value's own transaction (not used later here).
    op.execute("ALTER TYPE tasktype ADD VALUE 'email_prioritization'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('context_description', sa.Text(), nullable=False),
    sa.Column('context_tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('context_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_weights', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_rules', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_task_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('sender_role', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.Text(), nullable=True),
    sa.Column('has_attachment', sa.Boolean(), nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('business_impact', sa.Integer(), nullable=False),
    sa.Column('operational_relevance', sa.Integer(), nullable=False),
    sa.Column('deadline_pressure', sa.Integer(), nullable=False),
    sa.Column('security_risk', sa.Integer(), nullable=False),
    sa.Column('context_tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('expected_priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=True),
    sa.Column('triggered_rules', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_rationale', sa.Text(), nullable=True),
    sa.Column('priority_boundary_proximity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['email_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_task_items_scenario_id'), 'email_task_items', ['scenario_id'], unique=False)
    op.create_table('email_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('initial_priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=True),
    sa.Column('selected_priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=True),
    sa.Column('expected_priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_time_ms', sa.Integer(), nullable=True),
    sa.Column('changed_decision', sa.Boolean(), nullable=True),
    sa.Column('change_count', sa.Integer(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('accuracy_level', sa.Enum('EXACT', 'CLOSE', 'MISPRIORITIZED', 'SEVERELY_MISPRIORITIZED', name='accuracylevel'), nullable=True),
    sa.Column('aria_messages_before_decision', sa.Integer(), nullable=True),
    # create_type=False: 'managertone' already exists (created by the very
    # first migration, for manager_messages.tone) -- this column reuses it,
    # it must not try to CREATE TYPE it again.
    sa.Column('aria_supervision_level', PGEnum('bienveillant', 'neutre', 'exigeant', 'intrusif', name='managertone', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email_task_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'email_id', name='uq_email_decision_task_email')
    )
    op.create_index(op.f('ix_email_decisions_email_id'), 'email_decisions', ['email_id'], unique=False)
    op.create_index(op.f('ix_email_decisions_event_id'), 'email_decisions', ['event_id'], unique=False)
    op.create_index(op.f('ix_email_decisions_session_id'), 'email_decisions', ['session_id'], unique=False)
    op.create_index(op.f('ix_email_decisions_task_id'), 'email_decisions', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('scenario_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_tasks_scenario_id_email_scenarios', 'tasks', 'email_scenarios', ['scenario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_scenario_id_email_scenarios', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'scenario_id')
    op.drop_index(op.f('ix_email_decisions_task_id'), table_name='email_decisions')
    op.drop_index(op.f('ix_email_decisions_session_id'), table_name='email_decisions')
    op.drop_index(op.f('ix_email_decisions_event_id'), table_name='email_decisions')
    op.drop_index(op.f('ix_email_decisions_email_id'), table_name='email_decisions')
    op.drop_table('email_decisions')
    op.drop_index(op.f('ix_email_task_items_scenario_id'), table_name='email_task_items')
    op.drop_table('email_task_items')
    op.drop_table('email_scenarios')
    # ### end Alembic commands ###

    # Postgres has no DROP VALUE -- same rename/recreate/cast dance as
    # b3c4d4c7e67e's downgrade. Any existing email_prioritization rows fall
    # back to data_validation (lossy, dev-environment defensive coverage).
    op.execute("ALTER TYPE tasktype RENAME TO tasktype_new")
    op.execute(
        "CREATE TYPE tasktype AS ENUM "
        "('data_validation', 'document_organization', 'email_writing', 'urgent_request', 'image_matching')"
    )
    op.execute(
        """
        ALTER TABLE tasks
        ALTER COLUMN type TYPE tasktype
        USING (
            CASE type::text
                WHEN 'email_prioritization' THEN 'data_validation'
                ELSE type::text
            END
        )::tasktype
        """
    )
    op.execute(
        """
        ALTER TABLE task_templates
        ALTER COLUMN task_type TYPE tasktype
        USING (
            CASE task_type::text
                WHEN 'email_prioritization' THEN 'data_validation'
                ELSE task_type::text
            END
        )::tasktype
        """
    )
    op.execute("DROP TYPE tasktype_new")
