"""aria v2 fsm state and generation metadata

Revision ID: e5934618b1f3
Revises: 5d531d7e7924
Create Date: 2026-09-15 18:50:41.166677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM as PGEnum

# revision identifiers, used by Alembic.
revision: str = 'e5934618b1f3'
down_revision: Union[str, Sequence[str], None] = '5d531d7e7924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Unlike create_table (which auto-creates a referenced Enum type via an
    # event listener), add_column does NOT -- these two enum types are
    # genuinely new, so they must be created explicitly before the columns
    # that reference them.
    postgresql.ENUM('SEED', 'GENERATED', name='scenariosource').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('LLM', 'FALLBACK', 'SYSTEM', name='generationtype').create(op.get_bind(), checkfirst=True)

    # server_default (not just the model's client-side Python default) is
    # required on both NOT NULL enum adds below -- existing rows from
    # Task 02 testing need a real value the instant the column exists, not
    # just for future ORM inserts. create_type=False on both: the types
    # were just created explicitly above, this must not try again.
    op.add_column(
        'email_scenarios',
        sa.Column(
            'source', postgresql.ENUM('SEED', 'GENERATED', name='scenariosource', create_type=False),
            nullable=False, server_default='SEED',
        ),
    )
    op.add_column('email_scenarios', sa.Column('scenario_version', sa.String(), nullable=True))
    op.add_column(
        'manager_messages',
        sa.Column(
            'generation_type', postgresql.ENUM('LLM', 'FALLBACK', 'SYSTEM', name='generationtype', create_type=False),
            nullable=False, server_default='FALLBACK',
        ),
    )
    # create_type=False: 'managertone' already exists (created by the very
    # first migration) -- same fix as 5d531d7e7924's aria_supervision_level
    # column, this must not try to CREATE TYPE it again.
    op.add_column(
        'sessions',
        sa.Column('current_manager_tone', PGEnum('bienveillant', 'neutre', 'exigeant', 'intrusif', name='managertone', create_type=False), nullable=True),
    )
    op.add_column('sessions', sa.Column('pressure_history', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'pressure_history')
    op.drop_column('sessions', 'current_manager_tone')
    op.drop_column('manager_messages', 'generation_type')
    op.drop_column('email_scenarios', 'scenario_version')
    op.drop_column('email_scenarios', 'source')
    # ### end Alembic commands ###

    # Columns referencing these are gone as of the drops above -- safe to
    # drop the types themselves now (created explicitly in upgrade(), so
    # they don't get auto-dropped the way create_table-declared enums do).
    postgresql.ENUM(name='generationtype').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='scenariosource').drop(op.get_bind(), checkfirst=True)
