"""add difficulty pool cooldown state to sessions

Revision ID: e5e51961e0b6
Revises: 9275b1c84738
Create Date: 2026-08-16 13:05:35.568221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5e51961e0b6'
down_revision: Union[str, Sequence[str], None] = '9275b1c84738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_difficulty_pool', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('difficulty_pool_set_at_task_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'difficulty_pool_set_at_task_count')
    op.drop_column('sessions', 'last_difficulty_pool')
    # ### end Alembic commands ###
